### ISSUE TITLE
[rosrun] Couldn't find executable named aruco_node below tuw_marker_detection/tuw_aruco

### ISSUE THREAD

**Issue by rahulsharma11** [tuw-robotics/tuw_visual_marker#3] opened 2018-12-09 16:03 UTC
Hi,
I am using this project with ros-melodic.
After building i sourced the "tuw_marker_detection/tuw_aruco/build/devel/setup.bash"
Then after running "rosrun tuw_aruco aruco_node", i got error-

[rosrun] Couldn't find executable named aruco_node below /home/rahul/tuw_marker_detection/tuw_aruco
[rosrun] Found the following, but they're either not files,
[rosrun] or not executable:
[rosrun]   /home/rahul/tuw_marker_detection/tuw_aruco/build/devel/lib/tuw_aruco/aruco_node

Any suggestion?
Thanks.

**Comment by maxbader** [comment] 2018-12-10 07:47
Can you try to run it without rossrun within the /home/rahul/tuw_marker_detection/tuw_aruco/build/devel/lib/tuw_aruco/ folder
```
cd /home/rahul/tuw_marker_detection/tuw_aruco/build/devel/lib/tuw_aruco/
./aruco_node
```

**Comment by rahulsharma11** [comment] 2018-12-10 09:54
Hi,
I ran simple ./aruco_node then it just gets hang displaying nothing in terminal.

**Comment by maxbader** [comment] 2018-12-10 10:04
If the executable can not be found you have to check your build system. And do not forget to start the roscore first

**Comment by rahulsharma11** [comment] 2018-12-10 10:06
Hi,
I have started the roscore already. And i can found aruco_node in "tuw_marker_detection/tuw_aruco/build/devel/lib/tuw_aruco/" folder.

Is there any  output expected by ./aruco-node?

**Comment by yulan0215** [comment] 2020-07-14 16:17
> Hi,
> I have started the roscore already. And i can found aruco_node in "tuw_marker_detection/tuw_aruco/build/devel/lib/tuw_aruco/" folder.
> 
> Is there any output expected by ./aruco-node?

I have the same problem, did you solve it?

**Comment by doctorseus** [comment] 2020-08-31 12:40
Duplicate of #5

**Closed as completed by doctorseus** 2020-08-31 12:40 UTC

**Comment by doctorseus** [comment] 2020-08-31 12:43
@rahulsharma11 there is no output on stdout or err for aruco_node at the moment. If you have no core running it will print an error. I will consider printing a status message so it's easier to identify if it's running. By itself at the moment the node will just output messages which you could monitor with `rostopic echo` if a marker is found.
